"""added artist_img col to artist model

Revision ID: 96c7816a667b
Revises: da7bd9c3457f
Create Date: 2022-11-28 15:50:08.940289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c7816a667b'
down_revision = 'da7bd9c3457f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('artist_img', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'artist_img')
    # ### end Alembic commands ###
